(global.webpackJsonp=global.webpackJsonp||[]).push([["pages/comments/comments"],{1842:
/*!*****************************************!*\
  !*** ./src/pages/comments/comments.vue ***!
  \*****************************************/
/*! no static exports found */function(n,t,e){"use strict";e.r(t);var o=e(/*! ./comments.vue?vue&type=template&id=2642ee5b&filter-modules=%7B%7D& */1843),r=e(/*! ./comments.vue?vue&type=script&lang=js& */1845);for(var c in r)"default"!==c&&function(n){e.d(t,n,function(){return r[n]})}(c);var u=e(/*! ../../../node_modules/vue-loader/lib/runtime/componentNormalizer.js */10),s=Object(u.default)(r.default,o.render,o.staticRenderFns,!1,null,null,null);s.options.__file="src/pages/comments/comments.vue",t.default=s.exports},1843:
/*!**********************************************************************************************!*\
  !*** ./src/pages/comments/comments.vue?vue&type=template&id=2642ee5b&filter-modules=%7B%7D& ***!
  \**********************************************************************************************/
/*! exports provided: render, staticRenderFns */function(n,t,e){"use strict";e.r(t);var o=e(/*! -!../../../node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!../../../node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--15-0!../../../node_modules/@dcloudio/webpack-uni-mp-loader/lib/template.js!../../../node_modules/vue-loader/lib??vue-loader-options!../../../node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-custom-block-loader??ref--0-1!../../../node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./comments.vue?vue&type=template&id=2642ee5b&filter-modules=%7B%7D& */1844);e.d(t,"render",function(){return o.render}),e.d(t,"staticRenderFns",function(){return o.staticRenderFns})},1844:
/*!********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--15-0!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/template.js!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-custom-block-loader??ref--0-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./src/pages/comments/comments.vue?vue&type=template&id=2642ee5b&filter-modules=%7B%7D& ***!
  \********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
/*! exports provided: render, staticRenderFns */function(n,t,e){"use strict";e.r(t),e.d(t,"render",function(){return o}),e.d(t,"staticRenderFns",function(){return r});var o=function(){var n=this.$createElement;this._self._c},r=[];o._withStripped=!0},1845:
/*!******************************************************************!*\
  !*** ./src/pages/comments/comments.vue?vue&type=script&lang=js& ***!
  \******************************************************************/
/*! no static exports found */function(n,t,e){"use strict";e.r(t);var o=e(/*! -!../../../node_modules/babel-loader/lib!../../../node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!../../../node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js!../../../node_modules/vue-loader/lib??vue-loader-options!../../../node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-custom-block-loader??ref--0-1!../../../node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./comments.vue?vue&type=script&lang=js& */1846),r=e.n(o);for(var c in o)"default"!==c&&function(n){e.d(t,n,function(){return o[n]})}(c);t.default=r.a},1846:
/*!******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/babel-loader/lib!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-custom-block-loader??ref--0-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./src/pages/comments/comments.vue?vue&type=script&lang=js& ***!
  \******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
/*! no static exports found */function(n,t,e){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var o={name:"comments",components:{"app-comments":function(){return Promise.all(/*! import() | pages/comments/app-comments */[e.e("common/vendor"),e.e("pages/comments/app-comments")]).then(e.bind(null,/*! ./app-comments.vue */3266))}},data:function(){return{goodsId:null,onReachBottom:0}},onLoad:function(n){this.$commonLoad.onload(n),this.goodsId=n.goods_id},onReachBottom:function(){this.onReachBottom=Math.random()}};t.default=o}},[[1841,"common/runtime","common/vendor"]]]);
//# sourceMappingURL=../../../.sourcemap/mp-weixin/pages/comments/comments.js.map